export const Categories =[
    {
        id:1,
        name:"Shirts",
        checked:true,
    },
    {
        id:2,
        name:"Grooming",
        checked:false,
    },
    {
        id:3,
        name:"Pants",
        checked:true,
    },
    {
        id:4,
        name:"Pants",
        checked:true,
    },
    {
        id:5,
        name:"Pants",
        checked:true,
    },
    {
        id:6,
        name:"Pants",
        checked:true,
    },
    {
        id:7,
        name:"Pants",
        checked:true,
    },
    {
        id:8,
        name:"Pants",
        checked:true,
    },
    {
        id:9,
        name:"Pants",
        checked:true,
    },
    {
        id:10,
        name:"Pants",
        checked:true,
    },
    {
        id:11,
        name:"Pants",
        checked:true,
    },
    {
        id:12,
        name:"Pants",
        checked:true,
    },
    {
        id:13,
        name:"Pants",
        checked:true,
    },
    {
        id:14,
        name:"Pants",
        checked:true,
    },
    {
        id:15,
        name:"Pants",
        checked:true,
    },
    {
        id:16,
        name:"Pants",
        checked:true,
    },
    {
        id:17,
        name:"Pants",
        checked:true,
    },
    {
        id:18,
        name:"Pants",
        checked:true,
    },
    {
        id:19,
        name:"Pants",
        checked:true,
    },
    {
        id:20,
        name:"Pants",
        checked:true,
    },
    {
        id:21,
        name:"Pants",
        checked:true,
    },
    {
        id:22,
        name:"Pants",
        checked:true,
    },
    {
        id:23,
        name:"Pants",
        checked:true,
    },
    {
        id:24,
        name:"Pants",
        checked:true,
    },
    {
        id:25,
        name:"Pants",
        checked:true,
    },

]